export type FootballTrivia = { q: string; a: string; hard?: boolean };

export const FOOTBALL_TRIVIA_AR: FootballTrivia[] = [
  { q: "من فاز بكأس العالم 2022؟", a: "الارجنتين" },
  { q: "كم مرة فاز البرازيل بكأس العالم؟", a: "5" },
  { q: "من هداف كأس العالم 2018؟", a: "هاري كين" },
  { q: "في أي نادٍ يلعب كريستيانو رونالدو في السعودية؟", a: "النصر" },
  { q: "من هو الهداف التاريخي لدوري أبطال أوروبا؟", a: "رونالدو" },
  { q: "كم لاعباً في فريق كرة القدم على أرض الملعب؟", a: "11" },
  { q: "ما مدة الشوط الواحد في كرة القدم؟", a: "45" },
  { q: "من فاز بدوري أبطال أوروبا 2024؟", a: "ريال مدريد" },
  { q: "ما لقب منتخب البرازيل؟", a: "السامبا" },
  { q: "من سجل هدف يد الرب؟", a: "مارادونا" },
  { q: "في أي نادٍ بدأ ليونيل ميسي مسيرته؟", a: "برشلونة" },
  { q: "من فاز بالكرة الذهبية 2023؟", a: "ميسي" },
  { q: "ما اسم ملعب برشلونة الشهير؟", a: "كامب نو" },
  { q: "من هو مدرب مانشستر سيتي المعروف؟", a: "غوارديولا" },
  { q: "في أي دولة يلعب محمد صلاح مع المنتخب؟", a: "مصر" },
  { q: "من فاز بكأس العالم 2018؟", a: "فرنسا" },
  { q: "من فاز بكأس العالم 2014؟", a: "المانيا" },
  { q: "من فاز بكأس العالم 2010؟", a: "اسبانيا" },
  { q: "ما لون قميص منتخب البرازيل الأساسي؟", a: "اصفر" },
  { q: "كم خطاً أصفر يعني طرد؟", a: "2" },
  { q: "ما اسم منافسة ريال مدريد وبرشلونة؟", a: "الكلاسيكو" },
  { q: "من هو كابتن منتخب الأرجنتين في 2022؟", a: "ميسي" },
  { q: "في أي مدينة يلعب باريس سان جيرمان؟", a: "باريس" },
  { q: "ما اسم البطولة الأوروبية للمنتخبات؟", a: "يورو" },
  { q: "من فاز بيورو 2020؟", a: "ايطاليا" },
  { q: "كم مرة فازت إيطاليا بكأس العالم؟", a: "4" },
  { q: "من هو الهداف التاريخي لمنتخب البرتغال؟", a: "رونالدو" },
  { q: "في أي نادٍ لعب زين الدين زيدان كمدرب؟", a: "ريال مدريد" },
  { q: "من فاز بدوري أبطال أوروبا 2023؟", a: "مانشستر سيتي" },
  { q: "من هو حارس مرمى إسبانيا الأسطوري؟", a: "كاسياس" },
  { q: "من سجل هدف رأسية الشهير في نهائي 1998؟", a: "زيدان" },
  { q: "في أي نادٍ يلعب إيرلينغ هالاند؟", a: "مانشستر سيتي" },
  { q: "ما لقب منتخب ألمانيا؟", a: "المانشافت" },
  { q: "من فاز بكأس آسيا 2024؟", a: "قطر" },
  { q: "في أي نادٍ يلعب نيمار في السعودية؟", a: "الهلال" },
  { q: "من هو الهداف التاريخي لكأس العالم؟", a: "كلوزه" },
  { q: "كم مرة فازت فرنسا بكأس العالم؟", a: "2" },
  { q: "من فاز بكأس العالم 2006؟", a: "ايطاليا" },
  { q: "من فاز بكأس العالم 2002؟", a: "البرازيل" },
  { q: "من فاز بكأس العالم 1998؟", a: "فرنسا" },
  { q: "ما اسم ملعب مانشستر يونايتد؟", a: "اولد ترافورد" },
  { q: "من هو أسطورة ليفربول الإنجليزي؟", a: "جيرارد" },
  { q: "من فاز بالدوري الإسباني 2023-24؟", a: "ريال مدريد" },
  { q: "من فاز بالدوري الإنجليزي 2023-24؟", a: "مانشستر سيتي" },
  { q: "من هو مدرب ليفربول السابق الألماني؟", a: "كلوب" },
  { q: "في أي نادٍ يلعب فينيسيوس جونيور؟", a: "ريال مدريد" },
  { q: "كم عدد الكرات الذهبية التي فاز بها ميسي؟", a: "8" },
  { q: "كم عدد الكرات الذهبية التي فاز بها رونالدو؟", a: "5" },
  { q: "من هو الهداف التاريخي لريال مدريد؟", a: "رونالدو" },
  { q: "ما اسم ملعب يوفنتوس؟", a: "اليانز ستاديوم" },
  { q: "من فاز بكأس العالم 1994؟", a: "البرازيل" },
  { q: "من فاز بكأس العالم 1990؟", a: "المانيا" },
  { q: "من فاز بكأس العالم 1986؟", a: "الارجنتين" },
  { q: "من فاز بكأس العالم 1982؟", a: "ايطاليا" },
  { q: "من فاز بكأس العالم 1978؟", a: "الارجنتين" },
  { q: "من فاز بكأس العالم 1974؟", a: "المانيا" },
  { q: "من فاز بكأس العالم 1970؟", a: "البرازيل" },
  { q: "ما اسم كأس إفريقيا للأمم؟", a: "كاس افريقيا" },
  { q: "من فاز بكأس أفريقيا 2022؟", a: "السنغال" },
  { q: "في أي نادٍ يلعب ساديو ماني؟", a: "النصر" },
  { q: "ما اسم حارس مرمى إيطاليا الأسطوري؟", a: "بوفون" },
  { q: "من فاز بدوري أبطال أوروبا 2022؟", a: "ريال مدريد" },
  { q: "من فاز بدوري أبطال أوروبا 2021؟", a: "تشيلسي" },
  { q: "من فاز بدوري أبطال أوروبا 2020؟", a: "بايرن" },
  { q: "من فاز بدوري أبطال أوروبا 2019؟", a: "ليفربول" },
  { q: "من فاز بدوري أبطال أوروبا 2018؟", a: "ريال مدريد" },
  { q: "من فاز بالدوري الإيطالي 2023-24؟", a: "انتر" },
  { q: "من فاز بالدوري الألماني 2023-24؟", a: "بايرن" },
  { q: "ما اسم ملعب بايرن ميونخ؟", a: "اليانز ارينا" },
  { q: "في أي نادٍ لعب روبرت ليفاندوفسكي قبل برشلونة؟", a: "بايرن" },
  { q: "من وصل لنصف نهائي كأس العالم 2022 من العرب؟", a: "المغرب" },
  { q: "من فاز بكأس العالم للأندية 2023؟", a: "مانشستر سيتي" },
  { q: "من هو الهداف التاريخي لمانشستر يونايتد؟", a: "روي" },
  { q: "في أي نادٍ لعب ديفيد بيكهام؟", a: "مانشستر يونايتد" },
  { q: "من سجل هدف الفوز في نهائي 2014؟", a: "غوتزه" },
  { q: "ما لقب منتخب إنجلترا؟", a: "الاسود الثلاثة" },
  { q: "من فاز بالكرة الذهبية 2018؟", a: "مودريتش" },
  { q: "كم مرة فازت إنجلترا بكأس العالم؟", a: "1" },
  { q: "في أي عام فازت إنجلترا بكأس العالم؟", a: "1966" },
  { q: "من هو الهداف التاريخي لمنتخب البرازيل؟", a: "بيليه" },
  { q: "ما اسم ملعب ريال مدريد؟", a: "سانتياغو برنابيو" },
  { q: "من فاز بيورو 2016؟", a: "البرتغال" },
  { q: "من سجل هدف الفوز في نهائي يورو 2016؟", a: "ادير" },
  { q: "في أي نادٍ يلعب كيليان مبابي (2024)؟", a: "ريال مدريد" },
  { q: "من هو الهداف التاريخي لمنتخب فرنسا؟", a: "جيرو" },
  { q: "من فاز بكأس العالم 1930؟", a: "الاوروغواي" },
  { q: "في أي عام استضافت قطر كأس العالم؟", a: "2022" },
  { q: "في أي نادٍ يلعب كريم بنزيما في السعودية؟", a: "الاتحاد" },
  { q: "من فاز بدوري روشن 2023-24؟", a: "الهلال" },
  { q: "من هو أسطورة النصر السعودي؟", a: "ماجد عبدالله" },
  { q: "في أي نادٍ لعب رونالدو قبل النصر؟", a: "مانشستر يونايتد", hard: true },
  { q: "في أي نادٍ يلعب محمد صلاح؟", a: "ليفربول", hard: true },
  { q: "من هو مدرب منتخب السعودية 2022؟", a: "رينارد", hard: true },
  { q: "من فاز بكأس آسيا 2019؟", a: "قطر", hard: true },
  { q: "ما اسم منافسة الأهلي والزمالك؟", a: "القمة", hard: true },
  { q: "كم حكم في مباراة كرة القدم؟", a: "1", hard: true },
  { q: "من يلعب بيده في كرة القدم؟", a: "الحارس", hard: true },
  { q: "ما اسم البطولة القارية لأمريكا الجنوبية؟", a: "ليبرتادوريس", hard: true },
  { q: "من هو الهداف التاريخي للدوري الإسباني؟", a: "ميسي", hard: true },
  { q: "من فاز بالدوري الفرنسي 2023-24؟", a: "باريس", hard: true },
  { q: "ما اسم ملعب باريس سان جيرمان؟", a: "بارك دي برانس", hard: true },
  { q: "في أي نادٍ لعب مبابي قبل ريال مدريد؟", a: "باريس", hard: true },
  { q: "من هو مدرب برشلونة 2024؟", a: "فليك", hard: true },
  { q: "ما اسم كأس إنجلترا؟", a: "كاس الاتحاد", hard: true },
  { q: "كم هدفاً سجل كلوزه في المونديال؟", a: "16", hard: true },
  { q: "من هو أسطورة الأرجنتين بجانب ميسي؟", a: "مارادونا", hard: true },
  { q: "ما اسم ملعب ميلان وإنتر؟", a: "سان سيرو", hard: true },
  { q: "من فاز بالسكوديتو 2023-24؟", a: "انتر", hard: true },
  { q: "في أي نادٍ لعب باولو مالديني؟", a: "ميلان", hard: true },
  { q: "من فاز بدوري أبطال أوروبا 2014؟", a: "ريال مدريد", hard: true },
  { q: "من سجل هدف التعادل في نهائي 2014؟", a: "راموس", hard: true },
  { q: "ما اسم منافسة ميلان وإنتر؟", a: "ديربي ميلانو", hard: true },
  { q: "من فاز بدوري أبطال أفريقيا 2023؟", a: "الاهلي", hard: true },
  { q: "من هو الهداف التاريخي لدوري أبطال أفريقيا؟", a: "الشمراني", hard: true },
  { q: "في أي نادٍ يلعب كيفين دي بروين؟", a: "مانشستر سيتي", hard: true },
  { q: "من هو كابتن منتخب إسبانيا 2010؟", a: "كاسياس", hard: true },
  { q: "من فاز بكأس الكونفدرالية؟", a: "البرازيل", hard: true },
  { q: "ما اسم كأس العالم للأندية؟", a: "كاس العالم للاندية", hard: true },
  { q: "من سجل هاتريك في نهائي 1966؟", a: "هاتريك", hard: true },
  { q: "من هو الهداف التاريخي ليوفنتوس؟", a: "ديل بييرو", hard: true },
  { q: "من فاز بكأس العالم 1958؟", a: "البرازيل", hard: true },
  { q: "من فاز بكأس العالم 1962؟", a: "البرازيل", hard: true },
  { q: "من فاز بكأس العالم 1966؟", a: "انجلترا", hard: true },
  { q: "من هو الهداف التاريخي لمنتخب إنجلترا؟", a: "روي", hard: true },
  { q: "من فاز بكأس العالم 1954؟", a: "المانيا الغربية", hard: true },
  { q: "من فاز بكأس العالم 1950؟", a: "الاوروغواي", hard: true },
  { q: "ما اسم منافسة روما ولاتسيو؟", a: "ديربي العاصمة", hard: true },
  { q: "من هو الهداف التاريخي لباريس سان جيرمان؟", a: "كافاني", hard: true },
  { q: "من فاز بكأس الاتحاد الإنجليزي 2024؟", a: "مانشستر سيتي", hard: true },
  { q: "من هو مدرب إيطاليا في يورو 2020؟", a: "مانشيني", hard: true },
  { q: "من هو الهداف التاريخي لبايرن ميونخ؟", a: "مولر", hard: true },
  { q: "من فاز بكأس العالم 2006 هدافاً؟", a: "كلوزه", hard: true },
  { q: "في أي نادٍ لعب ريال مدريد أسطورة راؤول؟", a: "ريال مدريد", hard: true },
  { q: "من هو الهداف التاريخي لتشيلسي؟", a: "لامبارد", hard: true },
  { q: "من فاز بالدوري الهولندي غالباً؟", a: "اياكس", hard: true },
  { q: "ما اسم ملعب ليفربول؟", a: "انفيلد", hard: true },
  { q: "من هو الهداف التاريخي لأرسنال؟", a: "هنري", hard: true },
  { q: "من فاز بكأس العالم 2010 هدافاً؟", a: "فيلا", hard: true },
  { q: "من هو كابتن منتخب إيطاليا 2006؟", a: "كانافارو", hard: true },
  { q: "من فاز بكأس العالم 2002 هدافاً؟", a: "رونالدو", hard: true },
  { q: "من هو الهداف التاريخي لمانشستر سيتي؟", a: "aguero", hard: true },
  { q: "من فاز بكأس العالم 1998 هدافاً؟", a: "سوكر", hard: true },
  { q: "من هو الهداف التاريخي لمنتخب ألمانيا؟", a: "كلوزه", hard: true },
  { q: "من فاز بكأس العالم 1982 هدافاً؟", a: "باولي", hard: true },
  { q: "من هو الهداف التاريخي لمنتخب إسبانيا؟", a: "توريس", hard: true },
  { q: "من فاز بكأس العالم 1978 هدافاً؟", a: "كيمبس", hard: true },
  { q: "من هو الهداف التاريخي لمنتخب هولندا؟", a: "كرونك", hard: true },
  { q: "من فاز بكأس العالم 1970 هدافاً؟", a: "مولر", hard: true },
  { q: "من هو الهداف التاريخي لمنتخب إنجلترا الحديث؟", a: "روي", hard: true },
  { q: "من فاز بكأس العالم 1966 هدافاً؟", a: "اوستيل", hard: true },
];

export const FOOTBALL_TRIVIA_EN: FootballTrivia[] = [
  { q: "Who won the 2022 World Cup?", a: "Argentina" },
  { q: "How many World Cups has Brazil won?", a: "5" },
  { q: "2018 World Cup top scorer?", a: "Harry Kane" },
  { q: "Ronaldo Saudi club?", a: "Al Nassr" },
  { q: "UCL all-time top scorer?", a: "Ronaldo" },
  { q: "Players on pitch per team?", a: "11" },
  { q: "Minutes per half?", a: "45" },
  { q: "UCL 2024 winner?", a: "Real Madrid" },
  { q: "Brazil nickname?", a: "Samba" },
  { q: "Hand of God scorer?", a: "Maradona" },
  { q: "Messi started at?", a: "Barcelona" },
  { q: "Ballon d Or 2023?", a: "Messi" },
  { q: "Barcelona stadium?", a: "Camp Nou" },
  { q: "Man City coach?", a: "Guardiola" },
  { q: "Salah country?", a: "Egypt" },
  { q: "2018 World Cup winner?", a: "France" },
  { q: "2014 World Cup winner?", a: "Germany" },
  { q: "2010 World Cup winner?", a: "Spain" },
  { q: "Brazil shirt color?", a: "Yellow" },
  { q: "Yellow cards for red?", a: "2" },
  { q: "Real vs Barca rivalry?", a: "El Clasico" },
  { q: "Argentina captain 2022?", a: "Messi" },
  { q: "PSG city?", a: "Paris" },
  { q: "European nations cup?", a: "Euro" },
  { q: "Euro 2020 winner?", a: "Italy" },
  { q: "Italy World Cup wins?", a: "4" },
  { q: "Portugal all-time scorer?", a: "Ronaldo" },
  { q: "Zidane coached?", a: "Real Madrid" },
  { q: "UCL 2023 winner?", a: "Man City" },
  { q: "Spain legendary keeper?", a: "Casillas" },
  { q: "1998 final header?", a: "Zidane" },
  { q: "Haaland club?", a: "Man City" },
  { q: "Germany nickname?", a: "Mannschaft" },
  { q: "Asian Cup 2024 winner?", a: "Qatar" },
  { q: "Neymar Saudi club?", a: "Al Hilal" },
  { q: "World Cup all-time scorer?", a: "Klose" },
  { q: "France World Cup wins?", a: "2" },
  { q: "2006 World Cup winner?", a: "Italy" },
  { q: "2002 World Cup winner?", a: "Brazil" },
  { q: "1998 World Cup winner?", a: "France" },
  { q: "Man United stadium?", a: "Old Trafford" },
  { q: "Liverpool legend?", a: "Gerrard" },
  { q: "La Liga 2023-24 winner?", a: "Real Madrid" },
  { q: "PL 2023-24 winner?", a: "Man City" },
  { q: "Liverpool German coach?", a: "Klopp" },
  { q: "Vinicius club?", a: "Real Madrid" },
  { q: "Messi Ballon d Or count?", a: "8" },
  { q: "Ronaldo Ballon d Or count?", a: "5" },
  { q: "Real all-time scorer?", a: "Ronaldo" },
  { q: "Juventus stadium?", a: "Allianz Stadium" },
  { q: "1994 World Cup winner?", a: "Brazil" },
  { q: "1990 World Cup winner?", a: "Germany" },
  { q: "1986 World Cup winner?", a: "Argentina" },
  { q: "1982 World Cup winner?", a: "Italy" },
  { q: "1978 World Cup winner?", a: "Argentina" },
  { q: "1974 World Cup winner?", a: "Germany" },
  { q: "1970 World Cup winner?", a: "Brazil" },
  { q: "AFCON name?", a: "AFCON" },
  { q: "AFCON 2022 winner?", a: "Senegal" },
  { q: "Mane club?", a: "Al Nassr" },
  { q: "Italy legendary keeper?", a: "Buffon" },
  { q: "UCL 2022 winner?", a: "Real Madrid" },
  { q: "UCL 2021 winner?", a: "Chelsea" },
  { q: "UCL 2020 winner?", a: "Bayern" },
  { q: "UCL 2019 winner?", a: "Liverpool" },
  { q: "UCL 2018 winner?", a: "Real Madrid" },
  { q: "Serie A 2023-24 winner?", a: "Inter" },
  { q: "Bundesliga 2023-24 winner?", a: "Bayern" },
  { q: "Bayern stadium?", a: "Allianz Arena" },
  { q: "Lewandowski before Barca?", a: "Bayern" },
  { q: "Arab WC 2022 semi-finalist?", a: "Morocco" },
  { q: "Club World Cup 2023 winner?", a: "Man City" },
  { q: "Man United all-time scorer?", a: "Rooney" },
  { q: "Beckham club?", a: "Man United" },
  { q: "2014 final winner goal?", a: "Gotze" },
  { q: "England nickname?", a: "Three Lions" },
  { q: "Ballon d Or 2018?", a: "Modric" },
  { q: "England World Cup wins?", a: "1" },
  { q: "England WC win year?", a: "1966" },
  { q: "Brazil all-time scorer?", a: "Pele" },
  { q: "Real stadium?", a: "Bernabeu" },
  { q: "Euro 2016 winner?", a: "Portugal" },
  { q: "Euro 2016 final scorer?", a: "Eder" },
  { q: "Mbappe club 2024?", a: "Real Madrid" },
  { q: "France all-time scorer?", a: "Giroud" },
  { q: "First World Cup winner?", a: "Uruguay" },
  { q: "Qatar WC year?", a: "2022" },
  { q: "Benzema Saudi club?", a: "Al Ittihad" },
  { q: "Saudi league 2023-24 winner?", a: "Al Hilal" },
  { q: "Al Nassr legend?", a: "Majed Abdullah" },
  { q: "Ronaldo before Al Nassr?", a: "Man United", hard: true },
  { q: "Salah club?", a: "Liverpool", hard: true },
  { q: "Saudi coach 2022?", a: "Renard", hard: true },
  { q: "Asian Cup 2019 winner?", a: "Qatar", hard: true },
  { q: "Ahly vs Zamalek?", a: "Cairo Derby", hard: true },
  { q: "Referees on pitch?", a: "1", hard: true },
  { q: "Who can use hands?", a: "Goalkeeper", hard: true },
  { q: "South America club cup?", a: "Libertadores", hard: true },
  { q: "La Liga all-time scorer?", a: "Messi", hard: true },
  { q: "Ligue 1 2023-24 winner?", a: "PSG", hard: true },
  { q: "PSG stadium?", a: "Parc des Princes", hard: true },
  { q: "Mbappe before Real?", a: "PSG", hard: true },
  { q: "Barca coach 2024?", a: "Flick", hard: true },
  { q: "FA Cup name?", a: "FA Cup", hard: true },
  { q: "Klose WC goals?", a: "16", hard: true },
  { q: "Argentina legend besides Messi?", a: "Maradona", hard: true },
  { q: "Milan Inter stadium?", a: "San Siro", hard: true },
  { q: "Scudetto 2023-24?", a: "Inter", hard: true },
  { q: "Maldini club?", a: "Milan", hard: true },
  { q: "UCL 2014 winner?", a: "Real Madrid", hard: true },
  { q: "2014 final equalizer?", a: "Ramos", hard: true },
  { q: "Milan derby name?", a: "Derby della Madonnina", hard: true },
  { q: "CAF CL 2023 winner?", a: "Al Ahly", hard: true },
  { q: "CAF CL all-time scorer?", a: "Al Shammari", hard: true },
  { q: "De Bruyne club?", a: "Man City", hard: true },
  { q: "Spain captain 2010?", a: "Casillas", hard: true },
  { q: "Confederations Cup winner often?", a: "Brazil", hard: true },
  { q: "Club World Cup name?", a: "Club World Cup", hard: true },
  { q: "1966 final hat-trick?", a: "Hurst", hard: true },
  { q: "Juve all-time scorer?", a: "Del Piero", hard: true },
  { q: "1958 World Cup winner?", a: "Brazil", hard: true },
  { q: "1962 World Cup winner?", a: "Brazil", hard: true },
  { q: "1966 World Cup winner?", a: "England", hard: true },
  { q: "England all-time scorer?", a: "Rooney", hard: true },
  { q: "1954 World Cup winner?", a: "West Germany", hard: true },
  { q: "1950 World Cup winner?", a: "Uruguay", hard: true },
  { q: "Roma Lazio derby?", a: "Derby della Capitale", hard: true },
  { q: "PSG all-time scorer?", a: "Cavani", hard: true },
  { q: "FA Cup 2024 winner?", a: "Man City", hard: true },
  { q: "Italy Euro 2020 coach?", a: "Mancini", hard: true },
  { q: "Bayern all-time scorer?", a: "Muller", hard: true },
  { q: "2006 WC golden boot?", a: "Klose", hard: true },
  { q: "Raul club?", a: "Real Madrid", hard: true },
  { q: "Chelsea all-time scorer?", a: "Lampard", hard: true },
  { q: "Dutch league dominant club?", a: "Ajax", hard: true },
  { q: "Liverpool stadium?", a: "Anfield", hard: true },
  { q: "Arsenal all-time scorer?", a: "Henry", hard: true },
  { q: "2010 WC golden boot?", a: "Villa", hard: true },
  { q: "Italy captain 2006?", a: "Cannavaro", hard: true },
  { q: "2002 WC golden boot?", a: "Ronaldo", hard: true },
  { q: "Man City all-time scorer?", a: "Aguero", hard: true },
  { q: "1998 WC golden boot?", a: "Suker", hard: true },
  { q: "Germany all-time scorer?", a: "Klose", hard: true },
  { q: "1982 WC golden boot?", a: "Paoli", hard: true },
  { q: "Spain all-time scorer?", a: "Torres", hard: true },
  { q: "1978 WC golden boot?", a: "Kempes", hard: true },
  { q: "Netherlands all-time scorer?", a: "Krol", hard: true },
  { q: "1970 WC golden boot?", a: "Muller", hard: true },
  { q: "England modern scorer?", a: "Rooney", hard: true },
  { q: "1966 WC golden boot?", a: "Eusebio", hard: true },
];
