import type { Locale } from "@/i18n/types";
import { FOOTBALL_TRIVIA_AR, FOOTBALL_TRIVIA_EN, type FootballTrivia } from "@/lib/football-trivia";

export type FootballPlayer = {
  id: string;
  name: string;
  aliases: string[];
  nationality: string;
  clubs: string[];
  position: string;
  /** Accent color for card */
  color: string;
};

export const FOOTBALL_PLAYERS_AR: FootballPlayer[] = [
  {
    id: "ronaldo",
    name: "كريستيانو رونالدو",
    aliases: ["رونالدو", "cr7", "cristiano", "كريستيانو"],
    nationality: "برتغالي",
    clubs: ["سبورتنج لشبونة", "مانشستر يونايتد", "ريال مدريد", "يوفنتوس", "النصر"],
    position: "مهاجم",
    color: "#eab308",
  },
  {
    id: "messi",
    name: "ليونيل ميسي",
    aliases: ["ميسي", "messi", "ليو"],
    nationality: "أرجنتيني",
    clubs: ["برشلونة", "باريس سان جيرمان", "إنتر ميامي"],
    position: "مهاجم",
    color: "#38bdf8",
  },
  {
    id: "mbappe",
    name: "كيليان مبابي",
    aliases: ["مبابي", "mbappe", "كيليان"],
    nationality: "فرنسي",
    clubs: ["موناكو", "باريس سان جيرمان", "ريال مدريد"],
    position: "مهاجم",
    color: "#3b82f6",
  },
  {
    id: "haaland",
    name: "إيرلينغ هالاند",
    aliases: ["هالاند", "haaland", "إيرلينغ"],
    nationality: "نرويجي",
    clubs: ["مولده", "دورتموند", "مانشستر سيتي"],
    position: "مهاجم",
    color: "#22c55e",
  },
  {
    id: "salah",
    name: "محمد صلاح",
    aliases: ["صلاح", "salah", "مو صلاح", "محمد"],
    nationality: "مصري",
    clubs: ["المقاصة", "بازل", "تشيلسي", "فيورنتينا", "روما", "ليفربول"],
    position: "جناح",
    color: "#ef4444",
  },
  {
    id: "benzema",
    name: "كريم بنزيما",
    aliases: ["بنزيما", "benzema", "كريم"],
    nationality: "فرنسي",
    clubs: ["ليون", "ريال مدريد", "الاتحاد"],
    position: "مهاجم",
    color: "#f97316",
  },
  {
    id: "neymar",
    name: "نيمار",
    aliases: ["نيمار", "neymar", "نيمار دا سيلفا"],
    nationality: "برازيلي",
    clubs: ["سانتوس", "برشلونة", "باريس سان جيرمان", "الهلال"],
    position: "جناح",
    color: "#a855f7",
  },
  {
    id: "modric",
    name: "لوكا مودريتش",
    aliases: ["مودريتش", "modric", "لوكا"],
    nationality: "كرواتي",
    clubs: ["دينامو زغرب", "توتنهام", "ريال مدريد"],
    position: "وسط",
    color: "#6366f1",
  },
  {
    id: "debruyne",
    name: "كيفين دي بروين",
    aliases: ["دي بروين", "de bruyne", "كيفين"],
    nationality: "بلجيكي",
    clubs: ["غينك", "تشيلسي", "فولفسبورغ", "مانشستر سيتي"],
    position: "وسط",
    color: "#0ea5e9",
  },
  {
    id: "vinicius",
    name: "فينيسيوس جونيور",
    aliases: ["فينيسيوس", "vinicius", "فيني"],
    nationality: "برازيلي",
    clubs: ["فلامينغو", "ريال مدريد"],
    position: "جناح",
    color: "#facc15",
  },
  {
    id: "lewandowski",
    name: "روبرت ليفاندوفسكي",
    aliases: ["ليفاندوفسكي", "lewandowski", "ليفا"],
    nationality: "بولندي",
    clubs: ["ليتش", "دورتموند", "بايرن ميونخ", "برشلونة"],
    position: "مهاجم",
    color: "#dc2626",
  },
  {
    id: "kane",
    name: "هاري كين",
    aliases: ["كين", "kane", "هاري"],
    nationality: "إنجليزي",
    clubs: ["توتنهام", "بايرن ميونخ"],
    position: "مهاجم",
    color: "#1d4ed8",
  },
  {
    id: "mane",
    name: "ساديو ماني",
    aliases: ["ماني", "mane", "ساديو"],
    nationality: "سنغالي",
    clubs: ["ساوثامبتون", "ليفربول", "بايرن ميونخ", "النصر"],
    position: "جناح",
    color: "#b91c1c",
  },
  {
    id: "zlatan",
    name: "زلاتان إبراهيموفيتش",
    aliases: ["زلاتان", "zlatan", "إبراهيموفيتش", "ibra"],
    nationality: "سويدي",
    clubs: ["مالمو", "أياكس", "يوفنتوس", "إنتر", "برشلونة", "ميلان", "باريس", "مانشستر يونايتد", "لوس أنجلوس"],
    position: "مهاجم",
    color: "#f59e0b",
  },
  {
    id: "xavi",
    name: "تشافي هيرنانديز",
    aliases: ["تشافي", "xavi"],
    nationality: "إسباني",
    clubs: ["برشلونة", "السد"],
    position: "وسط",
    color: "#2563eb",
  },
  {
    id: "iniesta",
    name: "أندريس إنييستا",
    aliases: ["إنييستا", "iniesta", "أندريس"],
    nationality: "إسباني",
    clubs: ["برشلونة", "فيسيل كوبي"],
    position: "وسط",
    color: "#7c3aed",
  },
  {
    id: "maradona",
    name: "دييغو مارادونا",
    aliases: ["مارادونا", "maradona", "دييغو"],
    nationality: "أرجنتيني",
    clubs: ["أرجنتينوس", "بوكا", "برشلونة", "نابولي"],
    position: "وسط هجومي",
    color: "#0284c7",
  },
  {
    id: "pele",
    name: "بيليه",
    aliases: ["بيليه", "pele", "إدسون"],
    nationality: "برازيلي",
    clubs: ["سانتوس", "كوزموس"],
    position: "مهاجم",
    color: "#ca8a04",
  },
  {
    id: "zidane",
    name: "زين الدين زيدان",
    aliases: ["زيدان", "zidane", "زيزو"],
    nationality: "فرنسي",
    clubs: ["كان", "بوردو", "يوفنتوس", "ريال مدريد"],
    position: "وسط",
    color: "#4f46e5",
  },
  {
    id: "henry",
    name: "تييري هنري",
    aliases: ["هنري", "henry", "تييري"],
    nationality: "فرنسي",
    clubs: ["موناكو", "يوفنتوس", "أرسنال", "برشلونة"],
    position: "مهاجم",
    color: "#dc2626",
  },
  {
    id: "gerrard",
    name: "ستيفن جيرارد",
    aliases: ["جيرارد", "gerrard", "ستيفن"],
    nationality: "إنجليزي",
    clubs: ["ليفربول", "لوس أنجلوس"],
    position: "وسط",
    color: "#ef4444",
  },
  {
    id: "lampard",
    name: "فرانك لامبارد",
    aliases: ["لامبارد", "lampard", "فرانك"],
    nationality: "إنجليزي",
    clubs: ["وست هام", "تشيلسي", "مانشستر سيتي"],
    position: "وسط",
    color: "#1e40af",
  },
  {
    id: "ramos",
    name: "سيرخيو راموس",
    aliases: ["راموس", "ramos", "سيرخيو"],
    nationality: "إسباني",
    clubs: ["إشبيلية", "ريال مدريد", "باريس", "النصر"],
    position: "مدافع",
    color: "#fbbf24",
  },
  {
    id: "buffon",
    name: "جيانلويجي بوفون",
    aliases: ["بوفون", "buffon"],
    nationality: "إيطالي",
    clubs: ["بارما", "يوفنتوس", "باريس"],
    position: "حارس",
    color: "#334155",
  },
  {
    id: "casillas",
    name: "إيكر كاسياس",
    aliases: ["كاسياس", "casillas", "إيكر"],
    nationality: "إسباني",
    clubs: ["ريال مدريد", "بورتو"],
    position: "حارس",
    color: "#64748b",
  },
  {
    id: "hakimi",
    name: "أشرف حكيمي",
    aliases: ["حكيمي", "hakimi", "أشرف"],
    nationality: "مغربي",
    clubs: ["ريال مدريد", "دورتموند", "إنتر", "باريس"],
    position: "ظهير",
    color: "#16a34a",
  },
  {
    id: "mahrez",
    name: "رياض محرز",
    aliases: ["محرز", "mahrez", "رياض"],
    nationality: "جزائري",
    clubs: ["لوهافر", "ليستر", "مانشستر سيتي", "الأهلي"],
    position: "جناح",
    color: "#22d3ee",
  },
  {
    id: "son",
    name: "سون هيونغ مين",
    aliases: ["سون", "son", "هيونغ مين"],
    nationality: "كوري جنوبي",
    clubs: ["هامبورغ", "باير ليفركوزن", "توتنهام"],
    position: "مهاجم",
    color: "#e11d48",
  },
  {
    id: "bellingham",
    name: "جود بيلينغهام",
    aliases: ["بيلينغهام", "bellingham", "جود"],
    nationality: "إنجليزي",
    clubs: ["بوروسيا دورتموند", "ريال مدريد"],
    position: "وسط",
    color: "#f8fafc",
  },
  {
    id: "pedri",
    name: "بيدري",
    aliases: ["pedri", "بيدرو"],
    nationality: "إسباني",
    clubs: ["لاس بالماس", "برشلونة"],
    position: "وسط",
    color: "#a78bfa",
  },
];

export const FOOTBALL_PLAYERS_EN: FootballPlayer[] = [
  {
    id: "ronaldo",
    name: "Cristiano Ronaldo",
    aliases: ["ronaldo", "cr7", "cristiano"],
    nationality: "Portuguese",
    clubs: ["Sporting CP", "Manchester United", "Real Madrid", "Juventus", "Al Nassr"],
    position: "Forward",
    color: "#eab308",
  },
  {
    id: "messi",
    name: "Lionel Messi",
    aliases: ["messi", "leo"],
    nationality: "Argentine",
    clubs: ["Barcelona", "PSG", "Inter Miami"],
    position: "Forward",
    color: "#38bdf8",
  },
  {
    id: "mbappe",
    name: "Kylian Mbappe",
    aliases: ["mbappe", "kylian"],
    nationality: "French",
    clubs: ["Monaco", "PSG", "Real Madrid"],
    position: "Forward",
    color: "#3b82f6",
  },
  {
    id: "haaland",
    name: "Erling Haaland",
    aliases: ["haaland", "erling"],
    nationality: "Norwegian",
    clubs: ["Molde", "Dortmund", "Man City"],
    position: "Forward",
    color: "#22c55e",
  },
  {
    id: "salah",
    name: "Mohamed Salah",
    aliases: ["salah", "mo salah", "mohamed"],
    nationality: "Egyptian",
    clubs: ["El Mokawloon", "Basel", "Chelsea", "Fiorentina", "Roma", "Liverpool"],
    position: "Winger",
    color: "#ef4444",
  },
  {
    id: "benzema",
    name: "Karim Benzema",
    aliases: ["benzema", "karim"],
    nationality: "French",
    clubs: ["Lyon", "Real Madrid", "Al Ittihad"],
    position: "Forward",
    color: "#f97316",
  },
  {
    id: "neymar",
    name: "Neymar",
    aliases: ["neymar"],
    nationality: "Brazilian",
    clubs: ["Santos", "Barcelona", "PSG", "Al Hilal"],
    position: "Winger",
    color: "#a855f7",
  },
  {
    id: "modric",
    name: "Luka Modric",
    aliases: ["modric", "luka"],
    nationality: "Croatian",
    clubs: ["Dinamo Zagreb", "Tottenham", "Real Madrid"],
    position: "Midfielder",
    color: "#6366f1",
  },
  {
    id: "debruyne",
    name: "Kevin De Bruyne",
    aliases: ["de bruyne", "debruyne", "kevin"],
    nationality: "Belgian",
    clubs: ["Genk", "Chelsea", "Wolfsburg", "Man City"],
    position: "Midfielder",
    color: "#0ea5e9",
  },
  {
    id: "vinicius",
    name: "Vinicius Junior",
    aliases: ["vinicius", "vini"],
    nationality: "Brazilian",
    clubs: ["Flamengo", "Real Madrid"],
    position: "Winger",
    color: "#facc15",
  },
  {
    id: "lewandowski",
    name: "Robert Lewandowski",
    aliases: ["lewandowski", "lewa"],
    nationality: "Polish",
    clubs: ["Lech", "Dortmund", "Bayern", "Barcelona"],
    position: "Forward",
    color: "#dc2626",
  },
  {
    id: "kane",
    name: "Harry Kane",
    aliases: ["kane", "harry"],
    nationality: "English",
    clubs: ["Tottenham", "Bayern"],
    position: "Forward",
    color: "#1d4ed8",
  },
  {
    id: "mane",
    name: "Sadio Mane",
    aliases: ["mane", "sadio"],
    nationality: "Senegalese",
    clubs: ["Southampton", "Liverpool", "Bayern", "Al Nassr"],
    position: "Winger",
    color: "#b91c1c",
  },
  {
    id: "zlatan",
    name: "Zlatan Ibrahimovic",
    aliases: ["zlatan", "ibra", "ibrahimovic"],
    nationality: "Swedish",
    clubs: ["Malmo", "Ajax", "Juventus", "Inter", "Barcelona", "Milan", "PSG", "Man United", "LA Galaxy"],
    position: "Forward",
    color: "#f59e0b",
  },
  {
    id: "xavi",
    name: "Xavi Hernandez",
    aliases: ["xavi"],
    nationality: "Spanish",
    clubs: ["Barcelona", "Al Sadd"],
    position: "Midfielder",
    color: "#2563eb",
  },
  {
    id: "iniesta",
    name: "Andres Iniesta",
    aliases: ["iniesta", "andres"],
    nationality: "Spanish",
    clubs: ["Barcelona", "Vissel Kobe"],
    position: "Midfielder",
    color: "#7c3aed",
  },
  {
    id: "maradona",
    name: "Diego Maradona",
    aliases: ["maradona", "diego"],
    nationality: "Argentine",
    clubs: ["Argentinos", "Boca", "Barcelona", "Napoli"],
    position: "Attacking midfielder",
    color: "#0284c7",
  },
  {
    id: "pele",
    name: "Pele",
    aliases: ["pele", "edson"],
    nationality: "Brazilian",
    clubs: ["Santos", "Cosmos"],
    position: "Forward",
    color: "#ca8a04",
  },
  {
    id: "zidane",
    name: "Zinedine Zidane",
    aliases: ["zidane", "zizou"],
    nationality: "French",
    clubs: ["Cannes", "Bordeaux", "Juventus", "Real Madrid"],
    position: "Midfielder",
    color: "#4f46e5",
  },
  {
    id: "henry",
    name: "Thierry Henry",
    aliases: ["henry", "thierry"],
    nationality: "French",
    clubs: ["Monaco", "Juventus", "Arsenal", "Barcelona"],
    position: "Forward",
    color: "#dc2626",
  },
  {
    id: "gerrard",
    name: "Steven Gerrard",
    aliases: ["gerrard", "steven"],
    nationality: "English",
    clubs: ["Liverpool", "LA Galaxy"],
    position: "Midfielder",
    color: "#ef4444",
  },
  {
    id: "lampard",
    name: "Frank Lampard",
    aliases: ["lampard", "frank"],
    clubs: ["West Ham", "Chelsea", "Man City"],
    nationality: "English",
    position: "Midfielder",
    color: "#1e40af",
  },
  {
    id: "ramos",
    name: "Sergio Ramos",
    aliases: ["ramos", "sergio"],
    nationality: "Spanish",
    clubs: ["Sevilla", "Real Madrid", "PSG", "Al Nassr"],
    position: "Defender",
    color: "#fbbf24",
  },
  {
    id: "buffon",
    name: "Gianluigi Buffon",
    aliases: ["buffon"],
    nationality: "Italian",
    clubs: ["Parma", "Juventus", "PSG"],
    position: "Goalkeeper",
    color: "#334155",
  },
  {
    id: "casillas",
    name: "Iker Casillas",
    aliases: ["casillas", "iker"],
    nationality: "Spanish",
    clubs: ["Real Madrid", "Porto"],
    position: "Goalkeeper",
    color: "#64748b",
  },
  {
    id: "hakimi",
    name: "Achraf Hakimi",
    aliases: ["hakimi", "achraf"],
    nationality: "Moroccan",
    clubs: ["Real Madrid", "Dortmund", "Inter", "PSG"],
    position: "Full-back",
    color: "#16a34a",
  },
  {
    id: "mahrez",
    name: "Riyad Mahrez",
    aliases: ["mahrez", "riyad"],
    nationality: "Algerian",
    clubs: ["Le Havre", "Leicester", "Man City", "Al Ahly"],
    position: "Winger",
    color: "#22d3ee",
  },
  {
    id: "son",
    name: "Son Heung-min",
    aliases: ["son", "heung min"],
    nationality: "South Korean",
    clubs: ["Hamburg", "Bayer Leverkusen", "Tottenham"],
    position: "Forward",
    color: "#e11d48",
  },
  {
    id: "bellingham",
    name: "Jude Bellingham",
    aliases: ["bellingham", "jude"],
    nationality: "English",
    clubs: ["Dortmund", "Real Madrid"],
    position: "Midfielder",
    color: "#f8fafc",
  },
  {
    id: "pedri",
    name: "Pedri",
    aliases: ["pedri", "pedro"],
    nationality: "Spanish",
    clubs: ["Las Palmas", "Barcelona"],
    position: "Midfielder",
    color: "#a78bfa",
  },
];

export function getFootballPlayers(locale: Locale): FootballPlayer[] {
  return locale === "en" ? FOOTBALL_PLAYERS_EN : FOOTBALL_PLAYERS_AR;
}

export function getFootballTrivia(locale: Locale): FootballTrivia[] {
  return locale === "en" ? FOOTBALL_TRIVIA_EN : FOOTBALL_TRIVIA_AR;
}
