import type { QuizQuestion } from "@/lib/quiz-pack";

export const QUIZ_BANK_EN: QuizQuestion[] = [
  { q: "What is the capital of Jordan?", a: "Amman" },
  { q: "How many pillars of Islam are there?", a: "5" },
  { q: "What is the first month of the Islamic calendar?", a: "Muharram" },
  { q: "In which country is Petra located?", a: "Jordan" },
  { q: "How many rak'ahs are in Fajr prayer?", a: "2" },
  { q: "Who is the final prophet in Islam?", a: "Muhammad" },
  { q: "What is the salt sea west of Jordan called?", a: "Dead Sea" },
  { q: "How many daily obligatory prayers are there?", a: "5" },
  { q: "What is Jordan's currency?", a: "Dinar" },
  { q: "In which Jordanian city is the Roman Amphitheater?", a: "Amman" },
  { q: "What is the largest continent?", a: "Asia" },
  { q: "What is the smallest continent?", a: "Australia" },
  { q: "How many continents are there?", a: "7" },
  { q: "What is the longest river in the world?", a: "Nile" },
  { q: "What is the largest ocean?", a: "Pacific" },
  { q: "What is the capital of Egypt?", a: "Cairo" },
  { q: "What is the capital of Saudi Arabia?", a: "Riyadh" },
  { q: "What is the capital of Palestine?", a: "Jerusalem" },
  { q: "What is the capital of Syria?", a: "Damascus" },
  { q: "What is the capital of Iraq?", a: "Baghdad" },
  { q: "What is the capital of Lebanon?", a: "Beirut" },
  { q: "What is the capital of the UAE?", a: "Abu Dhabi" },
  { q: "What is the capital of Kuwait?", a: "Kuwait" },
  { q: "What is the capital of Qatar?", a: "Doha" },
  { q: "What is the capital of Bahrain?", a: "Manama" },
  { q: "What is the capital of Oman?", a: "Muscat" },
  { q: "What is the capital of Yemen?", a: "Sanaa" },
  { q: "What is the capital of Morocco?", a: "Rabat" },
  { q: "What is the capital of Tunisia?", a: "Tunis" },
  { q: "What is the capital of Algeria?", a: "Algiers" },
  { q: "What is the capital of Libya?", a: "Tripoli" },
  { q: "What is the capital of Sudan?", a: "Khartoum" },
  { q: "How many letters are in the Arabic alphabet?", a: "28" },
  { q: "What is the first surah of the Quran?", a: "Al-Fatiha" },
  { q: "What is the last surah of the Quran?", a: "An-Nas" },
  { q: "How many juz' are in the Quran?", a: "30" },
  { q: "In which month do Muslims fast?", a: "Ramadan" },
  { q: "How many rak'ahs are in Dhuhr prayer?", a: "4" },
  { q: "How many planets are in our solar system?", a: "8" },
  { q: "What gas do plants absorb from the air?", a: "Carbon dioxide" },
  { q: "What is the capital of France?", a: "Paris" },
  { q: "What is the capital of Italy?", a: "Rome" },
  { q: "What is the capital of Spain?", a: "Madrid" },
  { q: "What is the capital of Germany?", a: "Berlin" },
  { q: "What is the capital of Canada?", a: "Ottawa" },
  { q: "What is the capital of Australia?", a: "Canberra" },
  { q: "What is the capital of Japan?", a: "Tokyo" },
  { q: "What is the capital of South Korea?", a: "Seoul" },
  { q: "What is the capital of India?", a: "New Delhi" },
  { q: "What is the capital of Brazil?", a: "Brasilia" },
  { q: "What is the capital of Argentina?", a: "Buenos Aires" },
  { q: "What is the capital of Kenya?", a: "Nairobi" },
  { q: "What is the capital of Nigeria?", a: "Abuja" },
  { q: "What is the capital of New Zealand?", a: "Wellington" },
  { q: "Which country is home to the city of Barcelona?", a: "Spain" },
  { q: "Which country is home to Mount Fuji?", a: "Japan" },
  { q: "Which continent contains the Sahara Desert?", a: "Africa" },
  { q: "Which ocean lies between Africa and Australia?", a: "Indian Ocean" },
  { q: "What is the largest country by area?", a: "Russia" },
  { q: "What is the smallest country in the world?", a: "Vatican City" },
  { q: "Which river flows through London?", a: "Thames" },
  { q: "Which river flows through Paris?", a: "Seine" },
  { q: "What is the highest mountain above sea level?", a: "Mount Everest" },
  { q: "What is the world's largest hot desert?", a: "Sahara" },
  { q: "Which imaginary line divides Earth into northern and southern halves?", a: "Equator" },
  { q: "What is the chemical symbol for gold?", a: "Au" },
  { q: "What is the chemical symbol for iron?", a: "Fe" },
  { q: "What is the chemical formula for water?", a: "H2O" },
  { q: "At what temperature does water freeze in Celsius?", a: "0" },
  { q: "At what temperature does water boil at sea level in Celsius?", a: "100" },
  { q: "What is the largest planet in our solar system?", a: "Jupiter" },
  { q: "Which planet is closest to the Sun?", a: "Mercury" },
  { q: "Which planet is known as the Red Planet?", a: "Mars" },
  { q: "Which planet is famous for its rings?", a: "Saturn" },
  { q: "What is Earth's natural satellite?", a: "Moon" },
  { q: "What force pulls objects toward Earth?", a: "Gravity" },
  { q: "What gas makes up most of Earth's atmosphere?", a: "Nitrogen" },
  { q: "What gas do humans need to breathe?", a: "Oxygen" },
  { q: "What process do plants use to make food from sunlight?", a: "Photosynthesis" },
  { q: "What is the hardest natural substance?", a: "Diamond" },
  { q: "What element is the main component of diamonds?", a: "Carbon" },
  { q: "How many bones are in a typical adult human body?", a: "206" },
  { q: "What is the largest organ of the human body?", a: "Skin" },
  { q: "Which organ pumps blood around the body?", a: "Heart" },
  { q: "How many chambers does the human heart have?", a: "4" },
  { q: "Which part of a plant absorbs water from the soil?", a: "Roots" },
  { q: "What is the center of an atom called?", a: "Nucleus" },
  { q: "What instrument measures temperature?", a: "Thermometer" },
  { q: "What instrument is used to view very small objects?", a: "Microscope" },
  { q: "What is the nearest star to Earth?", a: "Sun" },
  { q: "How many players does a soccer team have on the field?", a: "11" },
  { q: "How many minutes are in a standard soccer match before added time?", a: "90" },
  { q: "Which sport uses a racket and a shuttlecock?", a: "Badminton" },
  { q: "Which sport is played at Wimbledon?", a: "Tennis" },
  { q: "How many rings are on the Olympic flag?", a: "5" },
  { q: "In basketball, how many points is a free throw worth?", a: "1" },
  { q: "How many players from one team are on a basketball court?", a: "5" },
  { q: "Which sport uses the terms birdie and eagle?", a: "Golf" },
  { q: "Which country hosted the first modern Olympic Games?", a: "Greece" },
  { q: "How many bases are on a baseball field?", a: "4" },
  { q: "Which sport uses a pommel horse?", a: "Gymnastics" },
  { q: "What color jersey does the leader of the Tour de France wear?", a: "Yellow" },
  { q: "In which sport can a player score a touchdown?", a: "American football" },
  { q: "How many holes are played in a standard round of golf?", a: "18" },
  { q: "Which chess piece moves in an L shape?", a: "Knight" },
  { q: "Which ancient civilization built the pyramids at Giza?", a: "Ancient Egyptians" },
  { q: "Who was the first person to walk on the Moon?", a: "Neil Armstrong" },
  { q: "In what year did humans first land on the Moon?", a: "1969" },
  { q: "What was the name of the first crewed Moon-landing mission?", a: "Apollo 11" },
  { q: "Who wrote the United States Declaration of Independence?", a: "Thomas Jefferson" },
  { q: "Which city was buried by Mount Vesuvius in 79 CE?", a: "Pompeii" },
  { q: "Which empire used roads to connect much of ancient Europe?", a: "Roman Empire" },
  { q: "Who was the first emperor of Rome?", a: "Augustus" },
  { q: "Which document signed in 1215 limited the English king's power?", a: "Magna Carta" },
  { q: "Who was known as the Maid of Orleans?", a: "Joan of Arc" },
  { q: "Which explorer led the first expedition to circumnavigate the globe?", a: "Ferdinand Magellan" },
  { q: "In which country did the Renaissance begin?", a: "Italy" },
  { q: "Which wall fell in 1989, symbolizing the end of the Cold War?", a: "Berlin Wall" },
  { q: "Who discovered penicillin?", a: "Alexander Fleming" },
  { q: "Who developed the theory of relativity?", a: "Albert Einstein" },
  { q: "Who painted the Mona Lisa?", a: "Leonardo da Vinci" },
  { q: "Who wrote Romeo and Juliet?", a: "William Shakespeare" },
  { q: "Who wrote The Odyssey?", a: "Homer" },
  { q: "Who wrote Pride and Prejudice?", a: "Jane Austen" },
  { q: "Who wrote The Hobbit?", a: "J. R. R. Tolkien" },
  { q: "What is the name of the wizarding school in Harry Potter?", a: "Hogwarts" },
  { q: "Which animated film features a snowman named Olaf?", a: "Frozen" },
  { q: "What is the name of the cowboy toy in Toy Story?", a: "Woody" },
  { q: "Which superhero is also known as Bruce Wayne?", a: "Batman" },
  { q: "Which superhero carries a shield with a star?", a: "Captain America" },
  { q: "What fictional detective lives at 221B Baker Street?", a: "Sherlock Holmes" },
  { q: "Which musical instrument normally has 88 keys?", a: "Piano" },
  { q: "How many strings does a standard violin have?", a: "4" },
  { q: "Which artist painted The Starry Night?", a: "Vincent van Gogh" },
  { q: "What is the highest female singing voice?", a: "Soprano" },
  { q: "Which board game features properties, railroads, and rent?", a: "Monopoly" },
  { q: "What is the name of the lion hero in The Lion King?", a: "Simba" },
  { q: "Which film series features the character Luke Skywalker?", a: "Star Wars" },
  { q: "What is the name of Peter Pan's fairy companion?", a: "Tinker Bell" },
  { q: "Which author created the character Hercule Poirot?", a: "Agatha Christie" },
  { q: "What is the capital of Norway?", a: "Oslo" },
  { q: "What is the capital of Mexico?", a: "Mexico City" },
  { q: "Which country contains the ancient city of Machu Picchu?", a: "Peru" },
  { q: "Which sea separates Europe and Africa?", a: "Mediterranean Sea" },
  { q: "What is the largest island in the world?", a: "Greenland" },
  { q: "What is the fastest land animal?", a: "Cheetah" },
  { q: "What is the largest animal on Earth?", a: "Blue whale" },
  { q: "How many hearts does an octopus have?", a: "3" },
  { q: "What vitamin can the body produce with sunlight?", a: "Vitamin D" },
  { q: "What is the basic unit of life?", a: "Cell" },
  { q: "Which metal is liquid at room temperature?", a: "Mercury" },
  { q: "How many sides does a hexagon have?", a: "6" },
  { q: "What is the square root of 144?", a: "12" },
  { q: "How many points is a touchdown worth before the extra point?", a: "6" },
  { q: "In volleyball, how many players from one team are on court?", a: "6" },
  { q: "Which sport uses a puck?", a: "Ice hockey" },
  { q: "Which country won the first FIFA World Cup?", a: "Uruguay" },
  { q: "Which ancient people created democracy in Athens?", a: "Ancient Greeks" },
  { q: "Who was the first woman to fly solo across the Atlantic?", a: "Amelia Earhart" },
  { q: "Which invention is Johannes Gutenberg famous for improving?", a: "Printing press" },
  { q: "Who composed The Four Seasons?", a: "Antonio Vivaldi" },
  { q: "Which artist sculpted David and painted the Sistine Chapel ceiling?", a: "Michelangelo" },
  { q: "What is the name of the bear in The Jungle Book?", a: "Baloo" },
  { q: "Which game uses the pieces king, queen, bishop, and rook?", a: "Chess" },
  { q: "Which fictional character loses a glass slipper at a ball?", a: "Cinderella" },
];
