import type { QuizQuestion } from "@/lib/quiz-pack";

export const QUIZ_BANK_EN: QuizQuestion[] = [
  { q: "What is the capital of Jordan?", a: "Amman" },
  { q: "How many pillars of Islam are there?", a: "5" },
  { q: "What is the first month of the Islamic calendar?", a: "Muharram" },
  { q: "In which country is Petra located?", a: "Jordan" },
  { q: "How many rak'ahs are in Fajr prayer?", a: "2" },
  { q: "Who is the final prophet in Islam?", a: "Muhammad" },
  { q: "What is the salt sea west of Jordan called?", a: "Dead Sea" },
  { q: "How many daily obligatory prayers are there?", a: "5" },
  { q: "What is Jordan's currency?", a: "Dinar" },
  { q: "In which Jordanian city is the Roman Amphitheater?", a: "Amman" },
  { q: "What is the largest continent?", a: "Asia" },
  { q: "What is the smallest continent?", a: "Australia" },
  { q: "How many continents are there?", a: "7" },
  { q: "What is the longest river in the world?", a: "Nile" },
  { q: "What is the largest ocean?", a: "Pacific" },
  { q: "What is the capital of Egypt?", a: "Cairo" },
  { q: "What is the capital of Saudi Arabia?", a: "Riyadh" },
  { q: "What is the capital of Palestine?", a: "Jerusalem" },
  { q: "What is the capital of Syria?", a: "Damascus" },
  { q: "What is the capital of Iraq?", a: "Baghdad" },
  { q: "What is the capital of Lebanon?", a: "Beirut" },
  { q: "What is the capital of the UAE?", a: "Abu Dhabi" },
  { q: "What is the capital of Kuwait?", a: "Kuwait" },
  { q: "What is the capital of Qatar?", a: "Doha" },
  { q: "What is the capital of Bahrain?", a: "Manama" },
  { q: "What is the capital of Oman?", a: "Muscat" },
  { q: "What is the capital of Yemen?", a: "Sanaa" },
  { q: "What is the capital of Morocco?", a: "Rabat" },
  { q: "What is the capital of Tunisia?", a: "Tunis" },
  { q: "What is the capital of Algeria?", a: "Algiers" },
  { q: "What is the capital of Libya?", a: "Tripoli" },
  { q: "What is the capital of Sudan?", a: "Khartoum" },
  { q: "How many letters are in the Arabic alphabet?", a: "28" },
  { q: "What is the first surah of the Quran?", a: "Al-Fatiha" },
  { q: "What is the last surah of the Quran?", a: "An-Nas" },
  { q: "How many juz' are in the Quran?", a: "30" },
  { q: "In which month do Muslims fast?", a: "Ramadan" },
  { q: "How many rak'ahs are in Dhuhr prayer?", a: "4" },
  { q: "How many planets are in our solar system?", a: "8" },
  { q: "What gas do plants absorb from the air?", a: "Carbon dioxide" },
];
