import type { Riddle } from "@/lib/riddles";

export const RIDDLE_BANK_EN: Riddle[] = [
  {
    id: "silence-en",
    category: "Logic",
    lines: ["If you speak my name, you break me", "If you keep me, you own the place", "What am I?"],
    answer: "Silence",
    aliases: ["quiet", "stillness"],
    hint: "The loudest thing broken by a single word.",
  },
  {
    id: "echo-en",
    category: "Nature",
    lines: [
      "I answer in every language",
      "Yet I never speak a word of my own",
      "I live in mountains and empty rooms",
      "What am I?",
    ],
    answer: "Echo",
    aliases: ["an echo"],
    hint: "It repeats the last thing it heard… letter for letter.",
  },
  {
    id: "shadow-en",
    category: "Nature",
    lines: [
      "I walk with you but never touch the ground",
      "I am longest at dawn and dusk",
      "I vanish when the light is gone",
      "What am I?",
    ],
    answer: "Shadow",
    aliases: ["a shadow"],
    hint: "You cast it, but it is not you.",
  },
  {
    id: "clock-en",
    category: "Objects",
    lines: ["I have hands but cannot clap", "I have a face but no eyes", "I tick but never talk", "What am I?"],
    answer: "Clock",
    aliases: ["a clock", "watch"],
    hint: "Everyone watches it, but it watches no one.",
  },
  {
    id: "fire-en",
    category: "Elements",
    lines: ["I eat but never bite", "I drink but have no mouth", "I dance without legs", "What am I?"],
    answer: "Fire",
    aliases: ["flame", "a fire"],
    hint: "The more you feed it, the taller it grows.",
  },
  {
    id: "map-en",
    category: "Objects",
    lines: ["I show you the world without moving", "Cities sit on me but weigh nothing", "Fold me and I shrink", "What am I?"],
    answer: "Map",
    aliases: ["a map", "atlas"],
    hint: "Explorers trust me, but I never travel.",
  },
  {
    id: "keyboard-en",
    category: "Technology",
    lines: ["I have many keys but no locks", "I speak without a voice", "You touch me all day", "What am I?"],
    answer: "Keyboard",
    aliases: ["a keyboard"],
    hint: "Writers and gamers both depend on me.",
  },
  {
    id: "towel-en",
    category: "Household",
    lines: ["The more I dry, the wetter I get", "I hang around after a shower", "What am I?"],
    answer: "Towel",
    aliases: ["a towel"],
    hint: "It absorbs what you no longer want on your skin.",
  },
  {
    id: "stamp-en",
    category: "Objects",
    lines: ["I travel the world but stay in one corner", "I carry messages without legs", "What am I?"],
    answer: "Stamp",
    aliases: ["a stamp", "postage stamp"],
    hint: "Small square, big journey.",
  },
  {
    id: "coin-en",
    category: "Objects",
    lines: ["I have two faces but no body", "I jingle in pockets", "Heads or tails?", "What am I?"],
    answer: "Coin",
    aliases: ["a coin", "money"],
    hint: "Toss me and fate decides.",
  },
  {
    id: "river-en",
    category: "Nature",
    lines: ["I run but never walk", "I have a mouth but never speak", "I have a bed but never sleep", "What am I?"],
    answer: "River",
    aliases: ["a river", "stream"],
    hint: "Always moving toward the sea.",
  },
  {
    id: "teapot-en",
    category: "Household",
    lines: ["I get filled but never eat", "I pour but have no hands", "Steam is my breath", "What am I?"],
    answer: "Teapot",
    aliases: ["a teapot", "kettle"],
    hint: "Hosts greet guests with me in many cultures.",
  },
  {
    id: "footsteps-en",
    category: "Logic",
    lines: ["The more you take, the more you leave behind", "They mark where you have been", "What are they?"],
    answer: "Footsteps",
    aliases: ["steps", "footprints"],
    hint: "Invisible until you look back.",
  },
  {
    id: "age-en",
    category: "Logic",
    lines: ["I always go up but never come down", "Everyone gains me", "What am I?"],
    answer: "Age",
    aliases: ["years", "time"],
    hint: "Birthdays add to me every year.",
  },
  {
    id: "secret-en",
    category: "Logic",
    lines: ["Tell me and I am no longer what I was", "The more you share me, the less I am", "What am I?"],
    answer: "Secret",
    aliases: ["a secret"],
    hint: "Whispers keep me alive.",
  },
  {
    id: "hole-en",
    category: "Logic",
    lines: ["The more you take away from me", "The larger I become", "What am I?"],
    answer: "Hole",
    aliases: ["a hole"],
    hint: "A shovel can make me grow.",
  },
  {
    id: "candle-en",
    category: "Objects",
    lines: ["I am tall when I am young", "I am short when I am old", "What am I?"],
    answer: "Candle",
    aliases: ["a candle"],
    hint: "I give light while melting.",
  },
  {
    id: "needle-en",
    category: "Objects",
    lines: ["I have one eye but cannot see", "I help join what has been torn", "What am I?"],
    answer: "Needle",
    aliases: ["a needle", "sewing needle"],
    hint: "Thread passes through my eye.",
  },
  {
    id: "comb-en",
    category: "Objects",
    lines: ["I have many teeth but cannot bite", "I help put hair in order", "What am I?"],
    answer: "Comb",
    aliases: ["a comb"],
    hint: "You may keep me by a mirror.",
  },
  {
    id: "book-en",
    category: "Objects",
    lines: ["I have leaves but I am not a tree", "I have a spine but no bones", "What am I?"],
    answer: "Book",
    aliases: ["a book"],
    hint: "Open me to read.",
  },
  {
    id: "egg-en",
    category: "Nature",
    lines: ["I am a tiny house with no doors or windows", "Something living may wait inside", "What am I?"],
    answer: "Egg",
    aliases: ["an egg"],
    hint: "You must crack my shell.",
  },
  {
    id: "light-en",
    category: "Elements",
    lines: ["I fill a room but take up no space", "Darkness leaves when I arrive", "What am I?"],
    answer: "Light",
    aliases: ["the light", "sunlight"],
    hint: "A lamp can provide me.",
  },
  {
    id: "mirror-en",
    category: "Objects",
    lines: ["I show you exactly what is before me", "But keep no picture when you leave", "What am I?"],
    answer: "Mirror",
    aliases: ["a mirror", "reflection"],
    hint: "Look into me to see yourself.",
  },
  {
    id: "onion-en",
    category: "Food",
    lines: ["I wear many layers", "Taking them off may make you cry", "What am I?"],
    answer: "Onion",
    aliases: ["an onion"],
    hint: "A strong-smelling kitchen vegetable.",
  },
  {
    id: "cloud-en",
    category: "Nature",
    lines: ["I float without wings", "I cry without eyes", "What am I?"],
    answer: "Cloud",
    aliases: ["a cloud", "clouds"],
    hint: "My tears fall as rain.",
  },
  {
    id: "key-en",
    category: "Objects",
    lines: ["I have teeth but cannot chew", "I turn so that a door may open", "What am I?"],
    answer: "Key",
    aliases: ["a key"],
    hint: "I fit inside a lock.",
  },
  {
    id: "sponge-en",
    category: "Household",
    lines: ["I am full of holes", "Yet I can hold water", "What am I?"],
    answer: "Sponge",
    aliases: ["a sponge"],
    hint: "I help with washing.",
  },
  {
    id: "moon-en",
    category: "Nature",
    lines: ["I shine at night with borrowed light", "My shape seems to change through the month", "What am I?"],
    answer: "Moon",
    aliases: ["the moon"],
    hint: "I orbit Earth.",
  },
  {
    id: "wind-en",
    category: "Nature",
    lines: ["You can hear me and feel me", "But you can never see me", "What am I?"],
    answer: "Wind",
    aliases: ["the wind", "air"],
    hint: "I make leaves dance.",
  },
  {
    id: "rain-en",
    category: "Nature",
    lines: ["I fall from clouds but never get hurt", "I help gardens grow", "What am I?"],
    answer: "Rain",
    aliases: ["the rain", "rainfall"],
    hint: "Umbrellas open when I arrive.",
  },
  {
    id: "mountain-en",
    category: "Nature",
    lines: ["My feet are on the earth", "My head may be above the clouds", "What am I?"],
    answer: "Mountain",
    aliases: ["a mountain"],
    hint: "Climbers seek my summit.",
  },
  {
    id: "sleep-en",
    category: "Logic",
    lines: ["The more you chase me", "The harder I am to catch", "What am I?"],
    answer: "Sleep",
    aliases: ["sleeping", "slumber"],
    hint: "Close your eyes and relax.",
  },
  {
    id: "dream-en",
    category: "Logic",
    lines: ["I can take you anywhere while you stay in bed", "I often fade when you wake", "What am I?"],
    answer: "Dream",
    aliases: ["a dream", "dreaming"],
    hint: "A story seen during sleep.",
  },
  {
    id: "heart-en",
    category: "Body",
    lines: ["I work every moment but never take a break", "My steady beat keeps you alive", "What am I?"],
    answer: "Heart",
    aliases: ["the heart", "a heart"],
    hint: "I pump blood.",
  },
  {
    id: "eye-en",
    category: "Body",
    lines: ["I can cry without being sad", "I let you see without speaking", "What am I?"],
    answer: "Eye",
    aliases: ["an eye", "eyes"],
    hint: "One of two windows on your face.",
  },
  {
    id: "door-en",
    category: "Household",
    lines: ["I open to let you pass", "I close to keep things out", "What am I?"],
    answer: "Door",
    aliases: ["a door"],
    hint: "I swing on hinges.",
  },
  {
    id: "window-en",
    category: "Household",
    lines: ["I am an eye in a wall", "I let in light while keeping out weather", "What am I?"],
    answer: "Window",
    aliases: ["a window"],
    hint: "I am often made of glass.",
  },
  {
    id: "chair-en",
    category: "Household",
    lines: ["I have four legs but cannot walk", "I support you when you rest", "What am I?"],
    answer: "Chair",
    aliases: ["a chair", "seat"],
    hint: "Sit on me.",
  },
  {
    id: "table-en",
    category: "Household",
    lines: ["I have legs but never move", "Meals and games are placed on me", "What am I?"],
    answer: "Table",
    aliases: ["a table"],
    hint: "Chairs often surround me.",
  },
  {
    id: "pillow-en",
    category: "Household",
    lines: ["I hold your head all night", "But I have no hands", "What am I?"],
    answer: "Pillow",
    aliases: ["a pillow"],
    hint: "I rest at the top of a bed.",
  },
  {
    id: "bottle-en",
    category: "Objects",
    lines: ["I have a neck but no head", "I wear a cap but have no hair", "What am I?"],
    answer: "Bottle",
    aliases: ["a bottle"],
    hint: "I hold drinks.",
  },
  {
    id: "shirt-en",
    category: "Objects",
    lines: ["I have a neck but no head", "Two arms but no hands", "What am I?"],
    answer: "Shirt",
    aliases: ["a shirt"],
    hint: "You wear me on your upper body.",
  },
  {
    id: "shoe-en",
    category: "Objects",
    lines: ["I have a tongue but cannot taste", "I travel wherever your foot goes", "What am I?"],
    answer: "Shoe",
    aliases: ["a shoe", "shoes"],
    hint: "Tie my laces before walking.",
  },
  {
    id: "piano-en",
    category: "Music",
    lines: ["I have many keys but open no doors", "My voice can be soft or grand", "What am I?"],
    answer: "Piano",
    aliases: ["a piano"],
    hint: "Musicians press my black and white keys.",
  },
  {
    id: "bell-en",
    category: "Objects",
    lines: ["I have a tongue but cannot talk", "Shake me and I sing", "What am I?"],
    answer: "Bell",
    aliases: ["a bell"],
    hint: "My voice is a ring.",
  },
  {
    id: "soap-en",
    category: "Household",
    lines: ["I get smaller every time I clean you", "Water makes me slippery", "What am I?"],
    answer: "Soap",
    aliases: ["a bar of soap"],
    hint: "I make bubbles.",
  },
  {
    id: "eraser-en",
    category: "Objects",
    lines: ["I remove mistakes", "And grow smaller as I do my job", "What am I?"],
    answer: "Eraser",
    aliases: ["an eraser", "rubber"],
    hint: "Use me after a pencil.",
  },
  {
    id: "pencil-en",
    category: "Objects",
    lines: ["I leave a gray trail", "The more I work, the shorter I become", "What am I?"],
    answer: "Pencil",
    aliases: ["a pencil"],
    hint: "A sharpener restores my point.",
  },
  {
    id: "umbrella-en",
    category: "Objects",
    lines: ["I am a roof you carry", "I open when the rain comes", "What am I?"],
    answer: "Umbrella",
    aliases: ["an umbrella", "parasol"],
    hint: "I help keep you dry.",
  },
  {
    id: "scissors-en",
    category: "Objects",
    lines: ["I have two blades and two rings", "My jaws cut but never eat", "What am I?"],
    answer: "Scissors",
    aliases: ["a pair of scissors"],
    hint: "I cut paper and cloth.",
  },
  {
    id: "ladder-en",
    category: "Objects",
    lines: ["I have many steps but never walk", "People climb me while I stand still", "What am I?"],
    answer: "Ladder",
    aliases: ["a ladder"],
    hint: "I help you reach high places.",
  },
  {
    id: "bridge-en",
    category: "Places",
    lines: ["I stretch over water but never get wet", "I join two sides together", "What am I?"],
    answer: "Bridge",
    aliases: ["a bridge"],
    hint: "People and vehicles cross me.",
  },
  {
    id: "road-en",
    category: "Places",
    lines: ["People travel on me", "But I never go anywhere", "What am I?"],
    answer: "Road",
    aliases: ["a road", "street"],
    hint: "I connect one place to another.",
  },
  {
    id: "island-en",
    category: "Nature",
    lines: ["Water surrounds me on every side", "Yet I am not a boat", "What am I?"],
    answer: "Island",
    aliases: ["an island"],
    hint: "I am land in a sea or lake.",
  },
  {
    id: "desert-en",
    category: "Nature",
    lines: ["I am a sea without water", "My waves are made of sand", "What am I?"],
    answer: "Desert",
    aliases: ["a desert"],
    hint: "Rain is rare here.",
  },
  {
    id: "rainbow-en",
    category: "Nature",
    lines: ["I am a bow with no arrow", "I appear in colors after rain", "What am I?"],
    answer: "Rainbow",
    aliases: ["a rainbow"],
    hint: "Sunlight and raindrops create me.",
  },
  {
    id: "snowman-en",
    category: "Nature",
    lines: ["I am built in winter", "The sun makes me disappear", "What am I?"],
    answer: "Snowman",
    aliases: ["a snowman"],
    hint: "My body is made of snowballs.",
  },
  {
    id: "ice-en",
    category: "Elements",
    lines: ["I am born from water", "But warmth turns me back into it", "What am I?"],
    answer: "Ice",
    aliases: ["an ice cube", "frozen water"],
    hint: "I am cold and solid.",
  },
  {
    id: "smoke-en",
    category: "Elements",
    lines: ["I rise from fire", "You can see me but cannot hold me", "What am I?"],
    answer: "Smoke",
    aliases: ["the smoke"],
    hint: "I drift upward in gray clouds.",
  },
  {
    id: "darkness-en",
    category: "Elements",
    lines: ["I arrive when light leaves", "Even a small candle sends me away", "What am I?"],
    answer: "Darkness",
    aliases: ["the dark", "dark"],
    hint: "I fill an unlit room.",
  },
  {
    id: "stars-en",
    category: "Nature",
    lines: ["We sparkle in a roof no one can touch", "We appear when day is done", "What are we?"],
    answer: "Stars",
    aliases: ["the stars", "star"],
    hint: "Look high into the night sky.",
  },
  {
    id: "thunder-en",
    category: "Nature",
    lines: ["I roar without a mouth", "I follow a flash in a storm", "What am I?"],
    answer: "Thunder",
    aliases: ["the thunder"],
    hint: "Lightning is seen before I am heard.",
  },
  {
    id: "lightning-en",
    category: "Nature",
    lines: ["I split the sky in a bright instant", "I vanish before you can catch me", "What am I?"],
    answer: "Lightning",
    aliases: ["a lightning bolt", "lightning bolt"],
    hint: "I flash during storms.",
  },
  {
    id: "wave-en",
    category: "Nature",
    lines: ["I rush toward the shore", "Then break without being hurt", "What am I?"],
    answer: "Wave",
    aliases: ["a wave", "ocean wave"],
    hint: "The sea makes me.",
  },
  {
    id: "dew-en",
    category: "Nature",
    lines: ["I cover grass with tiny pearls at dawn", "The morning sun makes me vanish", "What am I?"],
    answer: "Dew",
    aliases: ["the dew", "dewdrops"],
    hint: "I am made of cool droplets.",
  },
  {
    id: "tree-en",
    category: "Nature",
    lines: ["I wear a green crown in summer", "I stand on one leg for years", "What am I?"],
    answer: "Tree",
    aliases: ["a tree"],
    hint: "My roots hold me to the ground.",
  },
  {
    id: "banana-en",
    category: "Food",
    lines: ["I wear a yellow coat", "You remove it before eating me", "What am I?"],
    answer: "Banana",
    aliases: ["a banana"],
    hint: "I am a curved fruit.",
  },
  {
    id: "corn-en",
    category: "Food",
    lines: ["I have ears but cannot hear", "My yellow kernels grow in rows", "What am I?"],
    answer: "Corn",
    aliases: ["an ear of corn", "maize"],
    hint: "I may pop when heated.",
  },
  {
    id: "potato-en",
    category: "Food",
    lines: ["I have many eyes but cannot see", "I grow beneath the ground", "What am I?"],
    answer: "Potato",
    aliases: ["a potato"],
    hint: "I can become fries.",
  },
  {
    id: "orange-en",
    category: "Food",
    lines: ["I am a color and a fruit", "Peel my skin to find juicy sections", "What am I?"],
    answer: "Orange",
    aliases: ["an orange"],
    hint: "My name describes my color.",
  },
  {
    id: "popcorn-en",
    category: "Food",
    lines: ["Heat makes me burst", "I become a fluffy movie snack", "What am I?"],
    answer: "Popcorn",
    aliases: ["popped corn"],
    hint: "I begin as a hard kernel.",
  },
  {
    id: "honey-en",
    category: "Food",
    lines: ["I am sweet liquid gold", "Busy insects make me from flowers", "What am I?"],
    answer: "Honey",
    aliases: ["the honey"],
    hint: "Bees store me in a hive.",
  },
  {
    id: "bee-en",
    category: "Animals",
    lines: ["I visit flowers and make something sweet", "I can defend myself with a sting", "What am I?"],
    answer: "Bee",
    aliases: ["a bee", "honeybee"],
    hint: "I live in a hive.",
  },
  {
    id: "spider-en",
    category: "Animals",
    lines: ["I build a home from thread I make myself", "I have eight legs", "What am I?"],
    answer: "Spider",
    aliases: ["a spider"],
    hint: "My web catches insects.",
  },
  {
    id: "turtle-en",
    category: "Animals",
    lines: ["I carry my home wherever I go", "I am known for moving slowly", "What am I?"],
    answer: "Turtle",
    aliases: ["a turtle", "tortoise"],
    hint: "My shell protects me.",
  },
  {
    id: "bat-en",
    category: "Animals",
    lines: ["I fly at night but I am not a bird", "I rest hanging upside down", "What am I?"],
    answer: "Bat",
    aliases: ["a bat"],
    hint: "I navigate using echoes.",
  },
  {
    id: "fish-en",
    category: "Animals",
    lines: ["I live in water but never drown", "I breathe without lungs", "What am I?"],
    answer: "Fish",
    aliases: ["a fish"],
    hint: "I use gills and fins.",
  },
  {
    id: "snail-en",
    category: "Animals",
    lines: ["I carry a spiral home", "I leave a silver trail behind", "What am I?"],
    answer: "Snail",
    aliases: ["a snail"],
    hint: "I move very slowly.",
  },
  {
    id: "octopus-en",
    category: "Animals",
    lines: ["I have three hearts and eight arms", "I live beneath the waves", "What am I?"],
    answer: "Octopus",
    aliases: ["an octopus"],
    hint: "I can release a cloud of ink.",
  },
  {
    id: "giraffe-en",
    category: "Animals",
    lines: ["My long neck reaches leafy treetops", "My coat is covered in patches", "What am I?"],
    answer: "Giraffe",
    aliases: ["a giraffe"],
    hint: "I am the tallest land animal.",
  },
  {
    id: "zebra-en",
    category: "Animals",
    lines: ["I look like a horse in striped pajamas", "No two of us have the same pattern", "What am I?"],
    answer: "Zebra",
    aliases: ["a zebra"],
    hint: "My stripes are black and white.",
  },
  {
    id: "kangaroo-en",
    category: "Animals",
    lines: ["I travel by jumping", "I carry my young in a pouch", "What am I?"],
    answer: "Kangaroo",
    aliases: ["a kangaroo"],
    hint: "I have powerful hind legs.",
  },
  {
    id: "woodpecker-en",
    category: "Animals",
    lines: ["I knock on trees but never enter", "My beak works like a tiny hammer", "What am I?"],
    answer: "Woodpecker",
    aliases: ["a woodpecker"],
    hint: "I am a bird seeking insects in wood.",
  },
  {
    id: "name-en",
    category: "Logic",
    lines: ["I belong to you", "But other people use me more than you do", "What am I?"],
    answer: "Name",
    aliases: ["your name", "a name"],
    hint: "People say me to get your attention.",
  },
  {
    id: "tomorrow-en",
    category: "Time",
    lines: ["I am always coming", "But when I arrive I have a different name", "What am I?"],
    answer: "Tomorrow",
    aliases: ["the future"],
    hint: "When I arrive, I become today.",
  },
  {
    id: "yesterday-en",
    category: "Time",
    lines: ["I was close but now am behind you", "You can remember me but never return", "What am I?"],
    answer: "Yesterday",
    aliases: ["the past"],
    hint: "I am the day before today.",
  },
  {
    id: "calendar-en",
    category: "Time",
    lines: ["I contain many dates but no fruit", "My pages disappear through the year", "What am I?"],
    answer: "Calendar",
    aliases: ["a calendar"],
    hint: "I organize days and months.",
  },
  {
    id: "minute-en",
    category: "Words",
    lines: ["You find me once in a minute", "Twice in a moment, but never in a thousand years", "What am I?"],
    answer: "M",
    aliases: ["the letter m", "letter m"],
    hint: "Look at the spelling, not the time.",
  },
  {
    id: "envelope-en",
    category: "Words",
    lines: ["What begins with E, ends with E", "And contains only one letter?"],
    answer: "Envelope",
    aliases: ["an envelope"],
    hint: "The letter inside is a message.",
  },
  {
    id: "wrong-en",
    category: "Words",
    lines: ["Which word is always spelled incorrectly", "In every dictionary?"],
    answer: "Incorrectly",
    aliases: ["the word incorrectly"],
    hint: "The answer is inside the question.",
  },
  {
    id: "alphabet-en",
    category: "Words",
    lines: ["What word contains twenty-six letters", "But has only three syllables?"],
    answer: "Alphabet",
    aliases: ["the alphabet"],
    hint: "It names all the letters.",
  },
  {
    id: "nothing-en",
    category: "Logic",
    lines: ["Poor people have me", "Rich people need me", "If you eat me, you will not survive", "What am I?"],
    answer: "Nothing",
    aliases: ["nothing at all"],
    hint: "The answer is an absence.",
  },
  {
    id: "breath-en",
    category: "Logic",
    lines: ["I am light as a feather", "Yet no one can hold me for very long", "What am I?"],
    answer: "Breath",
    aliases: ["your breath", "a breath"],
    hint: "You take me without hands.",
  },
  {
    id: "future-en",
    category: "Logic",
    lines: ["I am always ahead of you", "But can never be seen", "What am I?"],
    answer: "Future",
    aliases: ["the future"],
    hint: "I have not happened yet.",
  },
  {
    id: "promise-en",
    category: "Logic",
    lines: ["I can be made and kept", "Or broken without being touched", "What am I?"],
    answer: "Promise",
    aliases: ["a promise", "your word"],
    hint: "Words and trust create me.",
  },
  {
    id: "queue-en",
    category: "Words",
    lines: ["Four of my five letters make no sound", "Yet I am pronounced like my first letter", "What word am I?"],
    answer: "Queue",
    aliases: ["the word queue"],
    hint: "People form me while waiting.",
  },
  {
    id: "dozen-en",
    category: "Logic",
    lines: ["If there are twelve fish and half drown", "How many remain?"],
    answer: "12",
    aliases: ["twelve", "all twelve"],
    hint: "Fish do not drown.",
  },
  {
    id: "rooster-egg-en",
    category: "Logic",
    lines: ["A rooster sits on a roof facing east", "Which way does its egg roll?"],
    answer: "Roosters do not lay eggs",
    aliases: ["a rooster cannot lay eggs", "no egg"],
    hint: "Think about the bird, not the roof.",
  },
  {
    id: "electric-train-en",
    category: "Logic",
    lines: ["An electric train travels north", "The wind blows south", "Which way does its smoke go?"],
    answer: "There is no smoke",
    aliases: ["electric trains do not make smoke", "no smoke"],
    hint: "Its power source matters.",
  },
  {
    id: "months-en",
    category: "Logic",
    lines: ["Some months have thirty days and some have thirty-one", "How many have twenty-eight days?"],
    answer: "12",
    aliases: ["twelve", "all twelve", "all of them"],
    hint: "Every month reaches day twenty-eight.",
  },
  {
    id: "stairs-en",
    category: "Logic",
    lines: ["A one-story house is painted blue inside and out", "What color are its stairs?"],
    answer: "There are no stairs",
    aliases: ["no stairs", "it has no stairs"],
    hint: "Count the stories.",
  },
  {
    id: "wet-hair-en",
    category: "Logic",
    lines: ["A person stands in pouring rain with no hat or umbrella", "Not one hair gets wet. Why?"],
    answer: "They are bald",
    aliases: ["bald", "the person is bald", "no hair"],
    hint: "There may be no hair to wet.",
  },
  {
    id: "match-en",
    category: "Logic",
    lines: ["You enter a dark room with a candle, lamp, and fireplace", "You have one match. What do you light first?"],
    answer: "Match",
    aliases: ["the match"],
    hint: "You need it to light everything else.",
  },
  {
    id: "one-story-en",
    category: "Logic",
    lines: ["What building has the most stories", "Yet may be completely silent?"],
    answer: "Library",
    aliases: ["a library"],
    hint: "Its stories are inside books.",
  },
  {
    id: "bank-en",
    category: "Words",
    lines: ["I have branches but no leaves or fruit", "People visit me to store something valuable", "What am I?"],
    answer: "Bank",
    aliases: ["a bank"],
    hint: "My branches handle money.",
  },
  {
    id: "glove-en",
    category: "Objects",
    lines: ["I have four fingers and a thumb", "But I have no flesh or bones", "What am I?"],
    answer: "Glove",
    aliases: ["a glove"],
    hint: "A hand wears me.",
  },
  {
    id: "telephone-en",
    category: "Technology",
    lines: ["I can ring but have no finger", "I connect voices far apart", "What am I?"],
    answer: "Telephone",
    aliases: ["a telephone", "phone", "a phone"],
    hint: "Answer me when I ring.",
  },
  {
    id: "computer-mouse-en",
    category: "Technology",
    lines: ["I have no fur, but I am called a mouse", "I help a pointer move", "What am I?"],
    answer: "Computer mouse",
    aliases: ["mouse", "a computer mouse"],
    hint: "I sit beside a keyboard.",
  },
  {
    id: "email-en",
    category: "Technology",
    lines: ["I cross the world in seconds", "I carry words but need no stamp", "What am I?"],
    answer: "Email",
    aliases: ["an email", "electronic mail"],
    hint: "I arrive in an inbox.",
  },
  {
    id: "camera-en",
    category: "Technology",
    lines: ["I have one eye but cannot see as you do", "I capture moments and keep them", "What am I?"],
    answer: "Camera",
    aliases: ["a camera"],
    hint: "Press my shutter for a picture.",
  },
  {
    id: "battery-en",
    category: "Technology",
    lines: ["I have positive and negative sides", "I give power but grow weaker", "What am I?"],
    answer: "Battery",
    aliases: ["a battery"],
    hint: "Many portable devices need me.",
  },
  {
    id: "traffic-light-en",
    category: "Objects",
    lines: ["I have three eyes in three colors", "I tell travelers when to stop and go", "What am I?"],
    answer: "Traffic light",
    aliases: ["a traffic light", "stoplight"],
    hint: "I stand at road intersections.",
  },
  {
    id: "fence-en",
    category: "Objects",
    lines: ["I run around a yard but never move", "I mark a boundary", "What am I?"],
    answer: "Fence",
    aliases: ["a fence"],
    hint: "I may be made of wood or wire.",
  },
  {
    id: "chimney-en",
    category: "Household",
    lines: ["I have a mouth on a roof", "Smoke travels through me", "What am I?"],
    answer: "Chimney",
    aliases: ["a chimney"],
    hint: "I rise above a fireplace.",
  },
  {
    id: "clock-times-en",
    category: "Logic",
    lines: ["I strike once at one, twice at two", "And twelve times at noon", "What am I?"],
    answer: "Clock",
    aliases: ["a clock", "clock tower"],
    hint: "My chimes count the hour.",
  },
  {
    id: "waterfall-en",
    category: "Nature",
    lines: ["I fall all day but never get hurt", "I roar as I tumble over rock", "What am I?"],
    answer: "Waterfall",
    aliases: ["a waterfall"],
    hint: "I am a river dropping from a height.",
  },
  {
    id: "coconut-en",
    category: "Food",
    lines: ["I am hairy outside and contain water inside", "My hard shell hides white flesh", "What am I?"],
    answer: "Coconut",
    aliases: ["a coconut"],
    hint: "I grow on a tropical palm.",
  },
];
