import type { Riddle } from "@/lib/riddles";

export const RIDDLE_BANK_EN: Riddle[] = [
  {
    id: "silence-en",
    category: "Logic",
    lines: ["If you speak my name, you break me", "If you keep me, you own the place", "What am I?"],
    answer: "Silence",
    aliases: ["quiet", "stillness"],
    hint: "The loudest thing broken by a single word.",
  },
  {
    id: "echo-en",
    category: "Nature",
    lines: [
      "I answer in every language",
      "Yet I never speak a word of my own",
      "I live in mountains and empty rooms",
      "What am I?",
    ],
    answer: "Echo",
    aliases: ["an echo"],
    hint: "It repeats the last thing it heard… letter for letter.",
  },
  {
    id: "shadow-en",
    category: "Nature",
    lines: [
      "I walk with you but never touch the ground",
      "I am longest at dawn and dusk",
      "I vanish when the light is gone",
      "What am I?",
    ],
    answer: "Shadow",
    aliases: ["a shadow"],
    hint: "You cast it, but it is not you.",
  },
  {
    id: "clock-en",
    category: "Objects",
    lines: ["I have hands but cannot clap", "I have a face but no eyes", "I tick but never talk", "What am I?"],
    answer: "Clock",
    aliases: ["a clock", "watch"],
    hint: "Everyone watches it, but it watches no one.",
  },
  {
    id: "fire-en",
    category: "Elements",
    lines: ["I eat but never bite", "I drink but have no mouth", "I dance without legs", "What am I?"],
    answer: "Fire",
    aliases: ["flame", "a fire"],
    hint: "The more you feed it, the taller it grows.",
  },
  {
    id: "map-en",
    category: "Objects",
    lines: ["I show you the world without moving", "Cities sit on me but weigh nothing", "Fold me and I shrink", "What am I?"],
    answer: "Map",
    aliases: ["a map", "atlas"],
    hint: "Explorers trust me, but I never travel.",
  },
  {
    id: "keyboard-en",
    category: "Technology",
    lines: ["I have many keys but no locks", "I speak without a voice", "You touch me all day", "What am I?"],
    answer: "Keyboard",
    aliases: ["a keyboard"],
    hint: "Writers and gamers both depend on me.",
  },
  {
    id: "towel-en",
    category: "Household",
    lines: ["The more I dry, the wetter I get", "I hang around after a shower", "What am I?"],
    answer: "Towel",
    aliases: ["a towel"],
    hint: "It absorbs what you no longer want on your skin.",
  },
  {
    id: "stamp-en",
    category: "Objects",
    lines: ["I travel the world but stay in one corner", "I carry messages without legs", "What am I?"],
    answer: "Stamp",
    aliases: ["a stamp", "postage stamp"],
    hint: "Small square, big journey.",
  },
  {
    id: "coin-en",
    category: "Objects",
    lines: ["I have two faces but no body", "I jingle in pockets", "Heads or tails?", "What am I?"],
    answer: "Coin",
    aliases: ["a coin", "money"],
    hint: "Toss me and fate decides.",
  },
  {
    id: "river-en",
    category: "Nature",
    lines: ["I run but never walk", "I have a mouth but never speak", "I have a bed but never sleep", "What am I?"],
    answer: "River",
    aliases: ["a river", "stream"],
    hint: "Always moving toward the sea.",
  },
  {
    id: "teapot-en",
    category: "Household",
    lines: ["I get filled but never eat", "I pour but have no hands", "Steam is my breath", "What am I?"],
    answer: "Teapot",
    aliases: ["a teapot", "kettle"],
    hint: "Hosts greet guests with me in many cultures.",
  },
  {
    id: "footsteps-en",
    category: "Logic",
    lines: ["The more you take, the more you leave behind", "They mark where you have been", "What are they?"],
    answer: "Footsteps",
    aliases: ["steps", "footprints"],
    hint: "Invisible until you look back.",
  },
  {
    id: "age-en",
    category: "Logic",
    lines: ["I always go up but never come down", "Everyone gains me", "What am I?"],
    answer: "Age",
    aliases: ["years", "time"],
    hint: "Birthdays add to me every year.",
  },
  {
    id: "secret-en",
    category: "Logic",
    lines: ["Tell me and I am no longer what I was", "The more you share me, the less I am", "What am I?"],
    answer: "Secret",
    aliases: ["a secret"],
    hint: "Whispers keep me alive.",
  },
];
