/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as PhraseRouteImport } from './routes/phrase'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as RateRouteImport } from './routes/rate'
import { Route as SeatRouteImport } from './routes/seat'
import { Route as StreamersRouteImport } from './routes/streamers'
import { Route as VoteRouteImport } from './routes/vote'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const PhraseRoute = PhraseRouteImport.update({
  id: '/phrase',
  path: '/phrase',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const RateRoute = RateRouteImport.update({
  id: '/rate',
  path: '/rate',
  getParentRoute: () => rootRouteImport,
} as any)
const SeatRoute = SeatRouteImport.update({
  id: '/seat',
  path: '/seat',
  getParentRoute: () => rootRouteImport,
} as any)
const StreamersRoute = StreamersRouteImport.update({
  id: '/streamers',
  path: '/streamers',
  getParentRoute: () => rootRouteImport,
} as any)
const VoteRoute = VoteRouteImport.update({
  id: '/vote',
  path: '/vote',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/connect': typeof ConnectRoute
  '/contact': typeof ContactRoute
  '/phrase': typeof PhraseRoute
  '/quiz': typeof QuizRoute
  '/rate': typeof RateRoute
  '/seat': typeof SeatRoute
  '/streamers': typeof StreamersRoute
  '/vote': typeof VoteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/connect': typeof ConnectRoute
  '/contact': typeof ContactRoute
  '/phrase': typeof PhraseRoute
  '/quiz': typeof QuizRoute
  '/rate': typeof RateRoute
  '/seat': typeof SeatRoute
  '/streamers': typeof StreamersRoute
  '/vote': typeof VoteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/connect': typeof ConnectRoute
  '/contact': typeof ContactRoute
  '/phrase': typeof PhraseRoute
  '/quiz': typeof QuizRoute
  '/rate': typeof RateRoute
  '/seat': typeof SeatRoute
  '/streamers': typeof StreamersRoute
  '/vote': typeof VoteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/connect'
    | '/contact'
    | '/phrase'
    | '/quiz'
    | '/rate'
    | '/seat'
    | '/streamers'
    | '/vote'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/connect'
    | '/contact'
    | '/phrase'
    | '/quiz'
    | '/rate'
    | '/seat'
    | '/streamers'
    | '/vote'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/connect'
    | '/contact'
    | '/phrase'
    | '/quiz'
    | '/rate'
    | '/seat'
    | '/streamers'
    | '/vote'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ConnectRoute: typeof ConnectRoute
  ContactRoute: typeof ContactRoute
  PhraseRoute: typeof PhraseRoute
  QuizRoute: typeof QuizRoute
  RateRoute: typeof RateRoute
  SeatRoute: typeof SeatRoute
  StreamersRoute: typeof StreamersRoute
  VoteRoute: typeof VoteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phrase': {
      id: '/phrase'
      path: '/phrase'
      fullPath: '/phrase'
      preLoaderRoute: typeof PhraseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rate': {
      id: '/rate'
      path: '/rate'
      fullPath: '/rate'
      preLoaderRoute: typeof RateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seat': {
      id: '/seat'
      path: '/seat'
      fullPath: '/seat'
      preLoaderRoute: typeof SeatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/streamers': {
      id: '/streamers'
      path: '/streamers'
      fullPath: '/streamers'
      preLoaderRoute: typeof StreamersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vote': {
      id: '/vote'
      path: '/vote'
      fullPath: '/vote'
      preLoaderRoute: typeof VoteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ConnectRoute: ConnectRoute,
  ContactRoute: ContactRoute,
  PhraseRoute: PhraseRoute,
  QuizRoute: QuizRoute,
  RateRoute: RateRoute,
  SeatRoute: SeatRoute,
  StreamersRoute: StreamersRoute,
  VoteRoute: VoteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
